spring:
  application:
    name: news_analyzer_server_v1

  #MultiConfiguration files|properties|yml
  profiles:
    include:
      - api

  #Verification Code Sender Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #Datasource Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/news_analyzer_db"
    username: postgres
    password: test123
    hikari:
      schema: news_analyzer_db_schema
      pool-name: MainHikariPool
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000

  #JPA Configuration
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

#Logging Configuration
logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    dsd.springboot_crud_postgresql: DEBUG

#JWT Configuration
jwt:
  secret-key: ${SECRET_KEY}
  expiration: ${ACCESS_JWT_EXPIRATION} #15 minutes = 15 * 60 * 1000
  refresh-expiration: ${REFRESH_JWT_EXPIRATION} #14 days = 14 * 24 * 60 * 60 * 1000

app:
  cors:
    allowed-origins: "http://localhost:3000"